---
# tasks file for qbittorrent-nox
- name: Add qBittorrent repository
  ansible.builtin.apt_repository:
    repo: "ppa:qbittorrent-team/qbittorrent-{{ qbittorrent_nox_qbt_version }}"
    state: present
    update_cache: true
  become: true

- name: Install qBittorrent
  ansible.builtin.apt:
    name: qbittorrent-nox
    state: present
  become: true

- name: Create local user
  ansible.builtin.user:
    name: "{{ qbittorrent_nox_qbt_user }}"
    shell: /usr/sbin/nologin
    state: present
  become: true

- name: Create qBittorrent config directory
  ansible.builtin.file:
    state: directory
    path: "/home/{{ qbittorrent_nox_qbt_user }}/.config/qBittorrent/"
    owner: "{{ qbittorrent_nox_qbt_user }}"
    group: "{{ qbittorrent_nox_qbt_user }}"
    mode: "0755"
  become: true

- name: Create qBittorrent config file
  ansible.builtin.template:
    src: qBittorrent.conf.j2
    dest: "/home/{{ qbittorrent_nox_qbt_user }}/.config/qBittorrent/qBittorrent.conf"
    owner: "{{ qbittorrent_nox_qbt_user }}"
    group: "{{ qbittorrent_nox_qbt_user }}"
    mode: "0644"
    force: false
  become: true

- name: Create qBittorrent service file
  ansible.builtin.template:
    src: qbittorrent.service.j2
    dest: /etc/systemd/system/qbittorrent.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload systemd daemon

- name: Enable qBittorrent service
  ansible.builtin.systemd:
    name: qbittorrent
    enabled: true
    state: started
  become: true
